name = "team-service"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "team-db"
database_id = "4003d717-a41b-4f18-862f-0bd680da038f"

