import './global.css';
import { ClerkProvider } from '@clerk/nextjs';

import { SidebarProvider } from '@team/source-ui';
import { TopNavBar } from './_components/navBar/TopNavBar';

export const metadata = {
  title: 'Welcome to dash',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { userId } = await auth();

  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      <html suppressHydrationWarning lang="en">
        <body>
          <SidebarProvider>
            <div className=" h-screen bg-gray-50">
              <TopNavBar />
              <main className="flex-1 overflow-y-auto p-8 text-gray-900">
                {children}
              </main>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
