import './global.css';
import { ClerkProvider } from '@clerk/nextjs';
// import { auth } from '@clerk/nextjs/server';
// import { Header } from './_components/Header';
import { SidebarProvider } from '@team/source-ui';
import { SideBarDash } from './_components/sideBar/SideBarDash';

export const metadata = {
  title: 'Welcome to dash',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { userId } = await auth();

  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      <html suppressHydrationWarning lang="en">
        <body>
          <SidebarProvider>
            <SideBarDash />
            {/* {userId && <Header />} */}
            {children}
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
