export const benefits = [
  {
    id: '1',
    title: 'Gym Membership',
    description: '50% subsidy for PineFit gym membership',
    subsidy: 50,
    vendor: 'PineFit',
    status: 'Active',
  },
  {
    id: '2',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Eligible',
  },
  {
    id: '3',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Pending',
  },
  {
    id: '4',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Locked',
  },
  {
    id: '5',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Active',
  },
  {
    id: '6',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Eligible',
  },
  {
    id: '7',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Pending',
  },
  {
    id: '8',
    title: 'Yoga Classes',
    description: 'Wellness yoga program',
    subsidy: 30,
    vendor: 'Yoga Center',
    status: 'Locked',
  },
];
